- id: 10.48550/arXiv.2306.08251
  image: https://bayesomicslab.github.io/images/bokeh.png
  tags:
    - machine learning
    - computer vision

- id: 10.48550/arXiv.2211.07105
  image: https://bayesomicslab.github.io/images/bamie_large.png
  tags:
    - computational biology
    - machine learning
    - algorithms

- id: 10.48550/arXiv.2210.06546
  image: https://bayesomicslab.github.io/images/goftest.png
  tags:
    - machine learning
    - computer vision

- id: 10.1016/j.osnem.2023.100249
  image: https://bayesomicslab.github.io/images/fakenews.png
  tags:
    - machine learning

- id: 10.1093/bioinformatics/btad220
  image: https://bayesomicslab.github.io/images/nonb_large.png
  tags:
    - computational biology
    - machine learning

- id: 10.48550/arXiv.2303.05015
  image: https://bayesomicslab.github.io/images/ssdistillation.png
  tags:
    - machine learning
    - computer vision

- id: 10.1089/cmb.2012.0084
  image: https://www.derekaguiar.com/images/hcgraph.png
  tags:
    - computational biology
    - algorithms
    - graph theory

- id: 10.1161/CIRCULATIONAHA.121.054285
  image: https://bayesomicslab.github.io/images/circulation_p.png
  tags:
    - computational biology
    - machine learning
    - immunology
    
- id: 10.1145/3462757.3466101
  image: https://bayesomicslab.github.io/images/icail_small.png
  tags:
    - machine learning
    - law
    
- id: 10.1101/2021.05.20.444959
  image: https://bayesomicslab.github.io/images/roberta_meth.png
  tags:
    - computational biology
    
- id: 10.1093/bioinformatics/btaa318
  image: https://bayesomicslab.github.io/images/exp_predict.png
  tags:
    - computational biology
    - machine learning
    
- id: 10.1038/s41467-018-03402-w
  image: https://bayesomicslab.github.io/images/biisq.png
  tags:
    - computational biology
    - machine learning
    
- id: 10.1109/CCWC54503.2022.9720799
  image: https://bayesomicslab.github.io/images/custout.png
  tags:
    - machine learning
    - time series
    - outage prediction
    
- id: 10.1093/bioinformatics/btt213
  image: https://bayesomicslab.github.io/images/compassgraph.png
  tags:
    - computational biology
    - algorithms
    - graph theory
    
- id: 10.1186/2041-9139-4-16
  tags:
    - computational biology
    
- id: 10.1371/journal.pone.0105097
  tags:
    - computational biology
    
- id: 10.1089/cmb.2010.0288
  image: https://bayesomicslab.github.io/images/clarkconsistgraph.png
  tags:
    - computational biology
    - algorithms
    - graph theory
    
- id: 10.1007/978-3-319-05269-4_1
  image: https://bayesomicslab.github.io/images/tractatus.png
  tags:
    - computational biology
    - algorithms
    - graph theory
    
- id: 10.1142/9789814335058_0010
  image: https://bayesomicslab.github.io/images/pphap.png
  tags:
    - computational biology
    - algorithms
    - graph theory
    
- id: 10.1007/978-1-60761-854-6_22
  image: https://bayesomicslab.github.io/images/cyrene.png
  tags:
    - computational biology
    - regulatory genomics

- id: 10.1142/9789814583220_0002
  image: https://bayesomicslab.github.io/images/tumorhap.png
  tags:
    - computational biology
    - algorithms
    - graph theory

- id: 10.1093/bioinformatics/bts234
  image: https://bayesomicslab.github.io/images/delish.png
  tags:
    - computational biology
    - algorithms
    - graph theory

- id: 10.1016/j.drudis.2022.103364
  image: https://bayesomicslab.github.io/images/alpay_drug.png
  tags:
    - computational biology

# - id: 
  # image: 
  # tags:
    # - computational biology
    # - algorithms
    # - graph theory
    # - machine learning
    # - 




# - id: doi:10.7554/eLife.32822
  # image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  # date: 2020-6-2
  # repo: greenelab/meta-review
  # extra-links:
    # - type: preprint
      # link: https://doi.org/10.7287/peerj.preprints.3100v1
    # - type: manubot
      # link: https://greenelab.github.io/scihub-manuscript/
    # - type: source
      # link: https://github.com/greenelab/scihub-manuscript
      # text: Manuscript source
    # - type: source
      # link: https://github.com/greenelab/scihub
      # text: Analyses source
